// Instagram Post starter — 1080×1080 square with a background image + dark
// overlay + centered title. Two variables: title (text) and imageUrl (bg).

import type { StarterTemplate } from "./starter-template-type";

export const instagramPostStarter: StarterTemplate = {
  id: "system-img-instagram-post",
  name: "Instagram Post",
  description: "1080×1080 square post with bold headline over a background image",
  platform: "instagram",
  layerData: {
    version: 1,
    width: 1080,
    height: 1080,
    backgroundColor: "#1e1b4b",
    layers: [
      {
        id: "bg-image",
        type: "image",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        rotation: 0,
        zIndex: 0,
        visible: true,
        locked: false,
        opacity: 1,
        src: "{{imageUrl}}",
        fitMode: "cover",
      },
      {
        id: "overlay",
        type: "rect",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: false,
        opacity: 0.45,
        fillColor: "#000000",
      },
      {
        id: "title",
        type: "text",
        x: 80,
        y: 420,
        width: 920,
        height: 240,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{title}}",
        fontFamily: "Be Vietnam Pro",
        fontSize: 92,
        fontWeight: 800,
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.1,
        letterSpacing: 0,
        textShadow: { x: 0, y: 4, blur: 16, color: "rgba(0,0,0,0.5)" },
      },
    ],
  },
  variables: [
    {
      name: "title",
      label: "Title",
      type: "text",
      defaultValue: "Your headline goes here",
      required: true,
      maxLength: 80,
    },
    {
      name: "imageUrl",
      label: "Background image",
      type: "image",
      defaultValue: "",
      required: false,
    },
  ],
};
