// LinkedIn Post starter — 1200×627 professional announcement card.

import type { StarterTemplate } from "./starter-template-type";

export const linkedinPostStarter: StarterTemplate = {
  id: "system-img-linkedin-post",
  name: "LinkedIn Post",
  description: "1200×627 announcement card with accent block, title, and body",
  platform: "linkedin",
  layerData: {
    version: 1,
    width: 1200,
    height: 627,
    backgroundColor: "#f8fafc",
    layers: [
      {
        id: "accent-block",
        type: "rect",
        x: 0,
        y: 0,
        width: 12,
        height: 627,
        rotation: 0,
        zIndex: 0,
        visible: true,
        locked: false,
        opacity: 1,
        fillColor: "#0a66c2",
      },
      {
        id: "eyebrow",
        type: "text",
        x: 80,
        y: 80,
        width: 1040,
        height: 40,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{eyebrow}}",
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: 600,
        color: "#0a66c2",
        textAlign: "left",
        lineHeight: 1,
        letterSpacing: 2,
      },
      {
        id: "title",
        type: "text",
        x: 80,
        y: 160,
        width: 1040,
        height: 240,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{title}}",
        fontFamily: "Inter",
        fontSize: 62,
        fontWeight: 700,
        color: "#0f172a",
        textAlign: "left",
        lineHeight: 1.15,
        letterSpacing: -0.5,
      },
      {
        id: "body",
        type: "text",
        x: 80,
        y: 440,
        width: 1040,
        height: 120,
        rotation: 0,
        zIndex: 3,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{body}}",
        fontFamily: "Inter",
        fontSize: 28,
        fontWeight: 400,
        color: "#475569",
        textAlign: "left",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
    ],
  },
  variables: [
    {
      name: "eyebrow",
      label: "Eyebrow",
      type: "text",
      defaultValue: "ANNOUNCEMENT",
      required: false,
      maxLength: 40,
    },
    {
      name: "title",
      label: "Title",
      type: "text",
      defaultValue: "We just launched something big",
      required: true,
      maxLength: 120,
    },
    {
      name: "body",
      label: "Body",
      type: "text",
      defaultValue: "A short paragraph explaining what and why.",
      required: false,
      maxLength: 200,
    },
  ],
};
