// Open Graph image starter — 1200×630 with a centered card layout over a
// gradient fill. Good for blog post share previews.

import type { StarterTemplate } from "./starter-template-type";

export const ogImageStarter: StarterTemplate = {
  id: "system-img-og-image",
  name: "Open Graph",
  description: "1200×630 link preview card — title + site name over a solid background",
  platform: "og-image",
  layerData: {
    version: 1,
    width: 1200,
    height: 630,
    backgroundColor: "#111827",
    layers: [
      {
        id: "accent-top",
        type: "rect",
        x: 0,
        y: 0,
        width: 1200,
        height: 10,
        rotation: 0,
        zIndex: 0,
        visible: true,
        locked: false,
        opacity: 1,
        fillColor: "{{accentColor}}",
      },
      {
        id: "title",
        type: "text",
        x: 80,
        y: 140,
        width: 1040,
        height: 280,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{title}}",
        fontFamily: "Be Vietnam Pro",
        fontSize: 68,
        fontWeight: 800,
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.15,
        letterSpacing: -0.5,
      },
      {
        id: "site-name",
        type: "text",
        x: 80,
        y: 510,
        width: 1040,
        height: 60,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{siteName}}",
        fontFamily: "Be Vietnam Pro",
        fontSize: 32,
        fontWeight: 500,
        color: "#9ca3af",
        textAlign: "left",
        lineHeight: 1,
        letterSpacing: 0,
      },
    ],
  },
  variables: [
    {
      name: "title",
      label: "Post title",
      type: "text",
      defaultValue: "How to build something great in 2026",
      required: true,
      maxLength: 120,
    },
    {
      name: "siteName",
      label: "Site name",
      type: "text",
      defaultValue: "yoursite.com",
      required: false,
      maxLength: 60,
    },
    {
      name: "accentColor",
      label: "Accent color",
      type: "color",
      defaultValue: "#6366f1",
      required: false,
    },
  ],
};
