// Quote Card starter — 1080×1080 square with large serif quote + author byline.

import type { StarterTemplate } from "./starter-template-type";

export const quoteCardStarter: StarterTemplate = {
  id: "system-img-quote-card",
  name: "Quote Card",
  description: "1080×1080 minimalist quote card with large serif type and author byline",
  platform: "generic",
  layerData: {
    version: 1,
    width: 1080,
    height: 1080,
    backgroundColor: "#fef3c7",
    layers: [
      {
        id: "border",
        type: "rect",
        x: 60,
        y: 60,
        width: 960,
        height: 960,
        rotation: 0,
        zIndex: 0,
        visible: true,
        locked: false,
        opacity: 1,
        fillColor: "#fef3c7",
        border: { width: 4, color: "#92400e" },
      },
      {
        id: "quote-mark",
        type: "text",
        x: 100,
        y: 120,
        width: 160,
        height: 180,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: false,
        opacity: 1,
        text: '"',
        fontFamily: "Playfair Display",
        fontSize: 220,
        fontWeight: 700,
        color: "#92400e",
        textAlign: "left",
        lineHeight: 1,
        letterSpacing: 0,
      },
      {
        id: "quote-text",
        type: "text",
        x: 120,
        y: 320,
        width: 840,
        height: 440,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{quote}}",
        fontFamily: "Playfair Display",
        fontSize: 56,
        fontWeight: 600,
        color: "#451a03",
        textAlign: "left",
        lineHeight: 1.3,
        letterSpacing: 0,
      },
      {
        id: "author",
        type: "text",
        x: 120,
        y: 820,
        width: 840,
        height: 80,
        rotation: 0,
        zIndex: 3,
        visible: true,
        locked: false,
        opacity: 1,
        text: "— {{author}}",
        fontFamily: "Be Vietnam Pro",
        fontSize: 36,
        fontWeight: 500,
        color: "#92400e",
        textAlign: "left",
        lineHeight: 1.2,
        letterSpacing: 1,
      },
    ],
  },
  variables: [
    {
      name: "quote",
      label: "Quote",
      type: "text",
      defaultValue: "Simplicity is the ultimate sophistication.",
      required: true,
      maxLength: 200,
    },
    {
      name: "author",
      label: "Author",
      type: "text",
      defaultValue: "Leonardo da Vinci",
      required: true,
      maxLength: 60,
    },
  ],
};
