// Twitter Card starter — 1200×675 with solid color background + title + subtitle.

import type { StarterTemplate } from "./starter-template-type";

export const twitterCardStarter: StarterTemplate = {
  id: "system-img-twitter-card",
  name: "Twitter Card",
  description: "1200×675 social card with title, subtitle, and accent bar",
  platform: "twitter",
  layerData: {
    version: 1,
    width: 1200,
    height: 675,
    backgroundColor: "#0f172a",
    layers: [
      {
        id: "accent-bar",
        type: "rect",
        x: 0,
        y: 0,
        width: 1200,
        height: 8,
        rotation: 0,
        zIndex: 0,
        visible: true,
        locked: false,
        opacity: 1,
        fillColor: "#38bdf8",
      },
      {
        id: "title",
        type: "text",
        x: 60,
        y: 180,
        width: 1080,
        height: 200,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{title}}",
        fontFamily: "Inter",
        fontSize: 72,
        fontWeight: 800,
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.15,
        letterSpacing: -1,
      },
      {
        id: "subtitle",
        type: "text",
        x: 60,
        y: 400,
        width: 1080,
        height: 120,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{subtitle}}",
        fontFamily: "Inter",
        fontSize: 32,
        fontWeight: 400,
        color: "#94a3b8",
        textAlign: "left",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
      {
        id: "handle",
        type: "text",
        x: 60,
        y: 580,
        width: 1080,
        height: 60,
        rotation: 0,
        zIndex: 3,
        visible: true,
        locked: false,
        opacity: 1,
        text: "{{handle}}",
        fontFamily: "Inter",
        fontSize: 28,
        fontWeight: 500,
        color: "#38bdf8",
        textAlign: "left",
        lineHeight: 1,
        letterSpacing: 0,
      },
    ],
  },
  variables: [
    {
      name: "title",
      label: "Headline",
      type: "text",
      defaultValue: "Your big headline",
      required: true,
      maxLength: 100,
    },
    {
      name: "subtitle",
      label: "Subtitle",
      type: "text",
      defaultValue: "A brief description or hook",
      required: false,
      maxLength: 160,
    },
    {
      name: "handle",
      label: "Handle",
      type: "text",
      defaultValue: "@yourbrand",
      required: false,
      maxLength: 40,
    },
  ],
};
