-- Update the dialogue template with full HTML and CSS
UPDATE "CmaTemplate" SET
  "htmlTemplate" = '<div class="tony-chat-wrapper" style="max-width: 850px; margin: 30px auto; background: #ffffff; border-radius: 16px; box-shadow: 0 10px 40px rgba(0,0,0,0.06); padding: 45px; border: 1px solid #f0f0f0;">
  <header style="text-align: center; margin-bottom: 50px; border-bottom: 2px solid #f8fafc; padding-bottom: 30px;">
    <h1 style="font-size: 2.2em; color: #1e293b; line-height: 1.3; margin-bottom: 15px; font-weight: 700;">[Tiêu đề bài viết]<br><span style="color: #2563eb;">[Phụ đề]</span></h1>
    <p style="color: #64748b; font-size: 1.1em; margin: 0 auto; font-style: italic; max-width: 700px; line-height: 1.6;">[Mô tả ngắn gọn về nội dung cuộc đối thoại]</p>
  </header>
  <div style="display: flex; flex-direction: column; gap: 35px;">
    <div style="display: flex; flex-direction: column; align-items: flex-start;"><div style="display: flex; align-items: center; margin-bottom: 8px;"><span style="width: 32px; height: 32px; background: #2563eb; color: white; display: flex; justify-content: center; align-items: center; border-radius: 50%; font-size: 14px; font-weight: bold; margin-right: 10px;">T</span><span style="font-weight: 700; color: #1e293b; font-size: 0.9em; text-transform: uppercase; letter-spacing: 1px;">Tony</span></div><div class="message-bubble" style="background-color: #f1f5f9; padding: 18px 25px; border-radius: 0 20px 20px 20px; border-left: 5px solid #2563eb; color: #334155; line-height: 1.7; max-width: 85%;"><p style="margin: 0;">[Câu hỏi hoặc nhận định của Tony]</p></div></div>
    <div style="display: flex; flex-direction: column; align-items: flex-end;"><div style="display: flex; align-items: center; margin-bottom: 8px; flex-direction: row-reverse;"><span style="width: 32px; height: 32px; background: #059669; color: white; display: flex; justify-content: center; align-items: center; border-radius: 50%; font-size: 14px; font-weight: bold; margin-left: 10px;">AI</span><span style="font-weight: 700; color: #1e293b; font-size: 0.9em; text-transform: uppercase; letter-spacing: 1px;">[Tiêu đề phân tích]</span></div><div class="message-bubble" style="background-color: #f0fdf4; padding: 25px; border-radius: 20px 0 20px 20px; border-right: 5px solid #059669; color: #1a2e21; line-height: 1.7; max-width: 90%; text-align: left; box-shadow: 0 4px 15px rgba(5, 150, 105, 0.05);"><p style="margin-top: 0;">[Nội dung phân tích của AI]</p><div style="margin: 20px 0;"><div class="ai-sub-card"><strong style="color: #059669; display: block; margin-bottom: 5px;">[Điểm 1]</strong><p style="margin: 0; font-size: 0.95em;">[Chi tiết điểm 1]</p></div><div class="ai-sub-card"><strong style="color: #059669; display: block; margin-bottom: 5px;">[Điểm 2]</strong><p style="margin: 0; font-size: 0.95em;">[Chi tiết điểm 2]</p></div></div><p style="margin-bottom: 0; color: #4b5563; font-style: italic; font-size: 0.95em;"><strong>[Kết luận]:</strong> [Nhận xét tổng kết]</p></div></div>
    <div style="display: flex; flex-direction: column; align-items: flex-start;"><div style="display: flex; align-items: center; margin-bottom: 8px;"><span style="width: 32px; height: 32px; background: #2563eb; color: white; display: flex; justify-content: center; align-items: center; border-radius: 50%; font-size: 14px; font-weight: bold; margin-right: 10px;">T</span><span style="font-weight: 700; color: #1e293b; font-size: 0.9em; text-transform: uppercase; letter-spacing: 1px;">Tony</span></div><div class="message-bubble" style="background-color: #f1f5f9; padding: 18px 25px; border-radius: 0 20px 20px 20px; border-left: 5px solid #2563eb; color: #334155; line-height: 1.7; max-width: 85%;"><p style="margin: 0;">[Phản biện hoặc câu hỏi tiếp theo]</p></div></div>
    <div style="display: flex; flex-direction: column; align-items: flex-end;"><div style="display: flex; align-items: center; margin-bottom: 8px; flex-direction: row-reverse;"><span style="width: 32px; height: 32px; background: #059669; color: white; display: flex; justify-content: center; align-items: center; border-radius: 50%; font-size: 14px; font-weight: bold; margin-left: 10px;">AI</span><span style="font-weight: 700; color: #1e293b; font-size: 0.9em; text-transform: uppercase; letter-spacing: 1px;">[Tiêu đề phản hồi]</span></div><div class="message-bubble" style="background-color: #f0fdf4; padding: 25px; border-radius: 20px 0 20px 20px; border-right: 5px solid #059669; color: #1a2e21; line-height: 1.7; max-width: 90%; text-align: left;"><p style="margin-top: 0;">[Nội dung phản hồi]</p><div class="ai-insight-box"><strong style="font-size: 1.1em; display: block; margin-bottom: 8px;">⚠️ [Tiêu đề insight]</strong><p style="margin: 0; line-height: 1.6; font-size: 0.95em;">[Nội dung insight quan trọng]</p></div></div></div>
    <div style="display: flex; flex-direction: column; align-items: flex-start;"><div style="display: flex; align-items: center; margin-bottom: 8px;"><span style="width: 32px; height: 32px; background: #2563eb; color: white; display: flex; justify-content: center; align-items: center; border-radius: 50%; font-size: 14px; font-weight: bold; margin-right: 10px;">T</span><span style="font-weight: 700; color: #1e293b; font-size: 0.9em; text-transform: uppercase; letter-spacing: 1px;">Tony</span></div><div class="message-bubble" style="background-color: #f1f5f9; padding: 18px 25px; border-radius: 0 20px 20px 20px; border-left: 5px solid #2563eb; color: #334155; line-height: 1.7; max-width: 85%;"><p style="margin: 0;">[Kết luận hoặc suy ngẫm cuối]</p></div></div>
    <div style="display: flex; flex-direction: column; align-items: flex-end;"><div style="display: flex; align-items: center; margin-bottom: 8px; flex-direction: row-reverse;"><span style="width: 32px; height: 32px; background: #059669; color: white; display: flex; justify-content: center; align-items: center; border-radius: 50%; font-size: 14px; font-weight: bold; margin-left: 10px;">AI</span><span style="font-weight: 700; color: #1e293b; font-size: 0.9em; text-transform: uppercase; letter-spacing: 1px;">[Kết nối hoàn tất]</span></div><div class="message-bubble" style="background-color: #f0fdf4; padding: 25px; border-radius: 20px 0 20px 20px; border-right: 5px solid #059669; color: #1a2e21; line-height: 1.7; max-width: 90%; text-align: left;"><p style="margin: 0;">[Lời kết thúc cuộc trò chuyện]</p></div></div>
  </div>
  <footer style="margin-top: 60px; padding-top: 30px; border-top: 1px solid #f1f5f9; text-align: center;"><p style="font-weight: 600; color: #64748b; font-size: 1.05em; line-height: 1.6; font-style: italic;">"[Trích dẫn kết thúc]"</p><div style="margin-top: 15px; color: #94a3b8; font-size: 0.8em; text-transform: uppercase; letter-spacing: 2px;">— Biên bản kết thúc —</div></footer>
</div>',
  "cssScoped" = '@media (max-width: 600px) { .tony-chat-wrapper { padding: 15px !important; margin: 10px !important; } h1 { font-size: 1.6em !important; } .message-bubble { max-width: 95% !important; padding: 15px !important; } .ai-sub-card { padding: 12px !important; } }
.ai-sub-card { background: #ffffff; padding: 15px; border-radius: 10px; border: 1px solid #dcfce7; margin-bottom: 12px; }
.ai-insight-box { margin-top: 20px; padding: 25px; background: #fffbeb; border: 1px solid #fef3c7; border-radius: 12px; color: #92400e; }'
WHERE id = 'tpl_dialogue_v1';
